image:
  flavor: apache

nextcloud:
  host: nextcloud.local
  username: admin
  password: change-me-now
  email: admin@example.local

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: local-selfsigned
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.local

persistence:
  enabled: true
  storageClass: hostpath
  accessMode: ReadWriteOnce
  size: 20Gi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: mysql
  host: nextcloud-mariadb
  database: nextcloud
  user: nextcloud
  password: change-db-password

mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: nextcloud
    username: nextcloud
    password: change-db-password
    rootPassword: change-root-password
  primary:
    persistence:
      enabled: true
      storageClass: hostpath
      size: 8Gi
  image:
    repository: docker.io/bitnami/mariadb
    tag: "11.2.4"

redis:
  enabled: true
  auth:
    password: change-redis-password
  master:
    persistence:
      enabled: true
  replica:
    persistence:
      enabled: true