grafana:
  adminPassword: change-me-now

  persistence:
    enabled: true
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: local-selfsigned
    hosts:
      - grafana.local
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.local

  defaultDashboardsEnabled: true

crds:
  enabled: true

nodeExporter:
  enabled: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.local
  prometheusSpec:
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

nodeExporter:
  enabled: true

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.local

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  
  tplConfig: true
  stringConfig: |
    global:
      resolve_timeout: 5m

    route:
      receiver: telegram
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h

    receivers:
      - name: telegram
        telegram_configs:
          - bot_token: "8309345928:AAFbBEg5amn0M7eisBWwxzR0sY8_jCzZ58"
            chat_id: "6452585600"
            send_resolved: true
            message: |
              🔥 {{ .CommonAnnotations.summary }}
              
              {{ .CommonAnnotations.description }}
              
              Severity: {{ .CommonLabels.severity }}