apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-issuers
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/kingtekillas/gitops.git
    targetRevision: main
    path: infrastructure/issuers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true